export const customers = [
    {
        id: 1,
        username: 'b.pandey',
        DOB: '13/06/1992',
        Fname: 'Bikeshwwar Pandey',
        Email: 'bikeshwattp@gmail.com',
        mobileNo: '9864356378',
        alternateMobileNo: '8767545543',
        Address: 'Sector-18',
        State: 'UP',
        City: 'Noida',
        pinCode: '201301',
        prefferdLocation: 'Bangalore',
        paymentDetails: '',
        subscription: '',
        license: '',
        education: {
            instituteName: 'ABC Institute',
            Qualification: 'B.Tech',
            Stream: 'CS',
            Status: 'test',
            Group: 'A',
            tenth: "90%",
            twelth: '90%',

        },
        physical: {
            Disabilities: 'No',
            Height: '6feet',
            Weight: '80kg',
            BMI: '',
            Career1: '',
            Career2: '',
            Remark: '',
        }
    },
    {
        id: 1,
        username: 'b.pandey',
        DOB: '13/06/1992',
        Fname: 'Bikeshwwar Pandey',
        Email: 'bikeshwattp@gmail.com',
        mobileNo: '9864356378',
        alternateMobileNo: '8767545543',
        Address: 'Sector-18',
        State: 'UP',
        City: 'Noida',
        pinCode: '201301',
        prefferdLocation: 'Bangalore',
        paymentDetails: '',
        subscription: '',
        license: '',
        education: {
            instituteName: 'ABC Institute',
            Qualification: 'B.Tech',
            Stream: 'CS',
            Status: 'test',
            Group: 'A',
            tenth: "90%",
            twelth: '90%',

        },
        physical: {
            Disabilities: 'No',
            Height: '6feet',
            Weight: '80kg',
            BMI: '',
            Career1: '',
            Career2: '',
            Remark: '',
        }
    }, {
        id: 1,
        username: 'b.pandey',
        DOB: '13/06/1992',
        Fname: 'Bikeshwwar Pandey',
        Email: 'bikeshwattp@gmail.com',
        mobileNo: '9864356378',
        alternateMobileNo: '8767545543',
        Address: 'Sector-18',
        State: 'UP',
        City: 'Noida',
        pinCode: '201301',
        prefferdLocation: 'Bangalore',
        paymentDetails: '',
        subscription: '',
        license: '',
        education: {
            instituteName: 'ABC Institute',
            Qualification: 'B.Tech',
            Stream: 'CS',
            Status: 'test',
            Group: 'A',
            tenth: "90%",
            twelth: '90%',

        },
        physical: {
            Disabilities: 'No',
            Height: '6feet',
            Weight: '80kg',
            BMI: '',
            Career1: '',
            Career2: '',
            Remark: '',
        }
    },
    {
        id: 1,
        username: 'b.pandey',
        DOB: '13/06/1992',
        Fname: 'Bikeshwwar Pandey',
        Email: 'bikeshwattp@gmail.com',
        mobileNo: '9864356378',
        alternateMobileNo: '8767545543',
        Address: 'Sector-18',
        State: 'UP',
        City: 'Noida',
        pinCode: '201301',
        prefferdLocation: 'Bangalore',
        paymentDetails: '',
        subscription: '',
        license: '',
        education: {
            instituteName: 'ABC Institute',
            Qualification: 'B.Tech',
            Stream: 'CS',
            Status: 'test',
            Group: 'A',
            tenth: "90%",
            twelth: '90%',

        },
        physical: {
            Disabilities: 'No',
            Height: '6feet',
            Weight: '80kg',
            BMI: '',
            Career1: '',
            Career2: '',
            Remark: '',
        }
    }

]